language: node_js
node_js: stable
install:
  - npm install
script:
  - hexo g
after_script:
  - cd ./public
  - git init 
  - git config user.name "houzixiashanxiedaima"
  - git config user.email "houzixiashanxiedaima@foxmail.com"
  - git add .
  - git commit -m "Travis CI Successfully"
  - git push --force --quiet "https://${Hexo_TOKEN}@${GH_REF}" master:master
branches:
  only:
    - hexo
env:
 global:
   - GH_REF: github.com/houzixiashanxiedaima/houzixiashanxiedaima.github.io.git
