language: node_js

node_js:
   --lts

# 缓存依赖
#cache:
#  directories:
#    - $HOME/.npm

before_install:
  - export TZ='Asia/Shanghai' # 更改时区

# 依赖安装
install:
  - npm install

# 构建脚本
script:
  # 先清除
  - hexo clean
    # 生成静态站点文件 使用主题自定义配置（高优先级） + 站点配置
  - hexo generate 
  # --config _config.yml,source/_data/next.yml

# 分支白名单
branches:
  only:
    - hexo # 只对 hexo 分支进行构建

# GitHub Pages 部署
deploy:
  provider: pages
  skip_cleanup: true
  # 在项目仪表盘的 Settings -> Environment Variables 中配置
  github_token: $Hexo_TOKEN
  # 将 public 目录下的内容推送到 master 分支上（必须）
  local_dir: public
  target-branch: master
  name: $GITHUB_NAME
  email: $GITHUB_EMAIL
  on:
    branch: hexo